### ISSUE TITLE
How can I attach to a specific pid whose program has many instances?

### ISSUE THREAD

**Issue by liming01** [gilligan/vim-lldb#9]
Hi guys, 

When I debug postgresql, which has many processes for one db instance, it reported below error:
Error during attach:  error: more than one process named ...

Thanks.

**Comment by liming01** [comment]
It seems even I run below command to attach pid, the following work can't continue.
-----------------------------------
:Lprocess attach --pid 1260
Process 1260 stopped
Executable module set to "/Users/ul1/postgresql/bin/postgres".
Architecture set to: i386-apple-macosx.
-----------------------------------
:Lshow backtrace:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mili/.vim/bundle/vim-lldb/python-vim-lldb/lldb_controller.py", line 281, in doShow
    self.ui.update(self.target, "", self)
  File "/Users/mili/.vim/bundle/vim-lldb/python-vim-lldb/vim_ui.py", line 193, in update
    self.paneCol.update(target, controller)
  File "/Users/mili/.vim/bundle/vim-lldb/python-vim-lldb/vim_panes.py", line 206, in update
    self.panes[name].update(target, controller)
  File "/Users/mili/.vim/bundle/vim-lldb/python-vim-lldb/vim_panes.py", line 305, in update
    self.apply_highlights()
  File "/Users/mili/.vim/bundle/vim-lldb/python-vim-lldb/vim_panes.py", line 330, in apply_highlights
    highlights = self.get_highlights()
  File "/Users/mili/.vim/bundle/vim-lldb/python-vim-lldb/vim_panes.py", line 580, in get_highlights
    line = self.get_selected_line()
  File "/Users/mili/.vim/bundle/vim-lldb/python-vim-lldb/vim_panes.py", line 635, in get_selected_line
    (frame, err) = get_selected_frame(self.target)
  File "/Users/mili/.vim/bundle/vim-lldb/python-vim-lldb/vim_panes.py", line 87, in get_selected_frame
    (thread, error) = get_selected_thread(target)
  File "/Users/mili/.vim/bundle/vim-lldb/python-vim-lldb/vim_panes.py", line 76, in get_selected_thread
    process = target.GetProcess()
AttributeError: 'NoneType' object has no attribute 'GetProcess'

**Comment by paulrouget** [comment]
Same issue here.
